import { Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "700", "200", "100"], // وزن‌هایی که نیاز داری
  display: "swap", // برای performance بهتر
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={notoSansArabic.className}>
      <body>{children}</body>
    </html>
  );
}
